### ISSUE TITLE
Multiple kotlin versions for gradle plugin

### ISSUE THREAD

**Issue by msasikanth** [saket/WYSIWYG#1]
Hello,

Any reason as to why you are using multiple kotlin version (1.3.10 & 1.3.21) in root gradle file?

https://github.com/saket/WYSIWYG/blob/2788abf7e70fcc5f1ee0b024100505ca525a11be/build.gradle#L24-L25

**Comment by saket** [comment]
Whoops! Not sure how I ended up with this. Fixed in 5e2ae196aaa0cc40e587cf77d2f5478469571101. Thanks @msasikanth!

**Comment by msasikanth** [comment]
Should I wait until release to file a issue related to crash I noticed?

**Comment by saket** [comment]
Go ahead an file it please
