### ISSUE TITLE
Creating new extension for Parser to use '~' for both StrikeThrough and Underline

### ISSUE THREAD

**Issue by msasikanth** [saket/WYSIWYG#3]
I have noticed there is no underline syntax available. So I have created a new extension and replaced StrikethroughExtension in FlexmarkMarkdownParser.

![carbon](https://user-images.githubusercontent.com/6140516/58611308-4ab7a780-82cc-11e9-8696-3d3853b5156d.png)
![carbon (1)](https://user-images.githubusercontent.com/6140516/58611310-4d1a0180-82cc-11e9-8cfc-54c1e8162d08.png)

This will allow us to use "~~" for StrikeThrough and "~" for Underlines.

Should I create a PR for this?

**Comment by msasikanth** [comment]
Sample app screenshots

![Screenshot_20190530-111727](https://user-images.githubusercontent.com/6140516/58611483-e8ab7200-82cc-11e9-8da7-3d8e8f6fac82.png)
![Screenshot_20190530-111743](https://user-images.githubusercontent.com/6140516/58611485-e8ab7200-82cc-11e9-9360-51e5eb5bf56b.png)

**Comment by msasikanth** [comment]
Another option to get same behaviour is setting `UNDERSCORE_DELIMITER_PROCESSOR` to false using `MutableDataSet` and pass it in `Parser` builder.

Then we can create underline only extension. I have checked flexmark for the UnderscoreDelimiterProcessor usage, it's usage is same as emphasis. So instead of that having underline seems like a good option?

![carbon](https://user-images.githubusercontent.com/6140516/58625134-713b0a00-82ef-11e9-9626-6a73c656710d.png)

**Comment by saket** [comment]
Sorry, just saw this. I've been really occupied relocating to a new country. 

Keeping the two extensions separate sounds like a better idea in case people don't want to use both. Could you please create a PR?

**Comment by msasikanth** [comment]
Is there a code style I have to follow? Because when I auto formatted it using studio indentation changed.

**Comment by msasikanth** [comment]
Created a PR : https://github.com/saket/WYSIWYG/pull/4

I have made it configurable by user. They just have to enable/disable it from MarkdownHintStyles, by default it's enabled.
