### ISSUE TITLE
Toggle markdown syntax visibility

### ISSUE THREAD

**Issue by msasikanth** [saket/WYSIWYG#5]
It would be great if the API enabled the option to let user toggle if they want the markdown syntax to be visible or not and still keep the formatting.

**Comment by saket** [comment]
Instead of providing a toggle in the library, I think it's better to do it on your side by keeping a reference to the text watcher.

```kotlin
val textWatcher = markdownHints.textWatcher()
    
if (markdownEnabled) {
  editText.addTextChangedListener(textWatcher)
} else {
  editText.removeTextChangedListener(textWatcher)
}
```
